version: "3.9"

networks:
  kul_k1:
    name: kul_k1

services:
  app:
    container_name: kul_k1-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - kul_k1

  mysql:
    container_name: kul_k1-mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kul_k1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    networks:
      - kul_k1

  web:
    container_name: kul_k1-web
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kul_k1

  phpmyadmin:
    container_name: kul_k1-phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "81:80"
    depends_on:
      - mysql
    links:
      - "mysql:db"
    networks:
      - kul_k1

  ################
  ##  Optional  ##
  ################

  # redis:
  #   container_name: kul_k1-redis
  #   image: redis:latest
  #   volumes:
  #     - ./docker/redis:/data
  #   ports:
  #     - "6380:6379"
  #   environment:
  #     - TZ=Asian/Jakarta
  #   networks:
  #     - kul_k1

  # rabbitmq:
  #   container_name: kul_k1-rabbitmq
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     - TZ=Asia/Jakarta
  #   volumes:
  #     - ./docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
  #     - ./docker/rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #     - kul_k1

